# Generated by Django 5.2.1 on 2025-05-21 01:50

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=200)),
                ('traducao', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('codigo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'dict_termos',
                'managed': False,
            },
        ),
    ]
